
const fs = require('fs');
const path = require('path');

const OUTPUT_FILE = path.resolve(__dirname, '../data/transport_data_osm.ts');

const LINES = [
    { ref: 'A', type: 'tram', color: 'E10D19', name: 'Parc des Sports - Illkirch Graffenstaden' },
    { ref: 'B', type: 'tram', color: '0099CC', name: 'Hoenheim Gare - Lingolsheim Tiergaertel' },
    { ref: 'C', type: 'tram', color: 'F68002', name: 'Gare Centrale - Neuhof Rodolphe Reuss' },
    { ref: 'D', type: 'tram', color: '007934', name: 'Poteries - Kehl Rathaus' },
    { ref: 'E', type: 'tram', color: '660099', name: 'Robertsau L\'Escale - Campus d\'Illkirch' },
    { ref: 'F', type: 'tram', color: '8CC63E', name: 'Place d\'Islande - Wolfisheim Henri Rendu' },
    // G and H often "bus" in OSM with ref=G / H
    { ref: 'G', type: 'bus', color: 'FFCC00', name: 'Espace Européen de l\'Entreprise - Rotterdam' },
    { ref: 'H', type: 'bus', color: '922b3e', name: 'Gare Centrale - Parlement Européen' },
];

async function fetchLine(lineRef, type) {
    // Overpass Query
    // Increased timeout to 90s
    // Added [maxsize: ...] locally if needed but public API usually limits time
    const query = `
        [out:json][timeout:90];
        (
          relation["route"="${type}"]["ref"="${lineRef}"](48.4,7.6,48.7,7.9);
        );
        out geom;
    `;

    const url = `https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`;
    console.log(`Fetching Line ${lineRef} from OSM...`);

    for (let i = 0; i < 3; i++) {
        try {
            const response = await fetch(url);
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            const data = await response.json();
            return data.elements;
        } catch (e) {
            console.error(`Attempt ${i + 1} failed for ${lineRef}:`, e.message);
            await new Promise(r => setTimeout(r, 2000 * (i + 1))); // Backoff
        }
    }
    return [];
}

function convertToGeoJSON(elements, lineInfo) {
    const coordinates = [];

    const IGNORED_ROLES = ['platform', 'stop', 'station', 'halt', 'platform_entry_only', 'platform_exit_only'];

    elements.forEach(rel => {
        if (rel.members) {
            rel.members.forEach(m => {
                // Filter only 'way' with geometry
                // Filter out non-track roles
                const role = (m.role || '').toLowerCase();
                if (IGNORED_ROLES.includes(role)) return;

                if (m.type === 'way' && m.geometry) {
                    const line = m.geometry.map(pt => [pt.lon, pt.lat]);
                    coordinates.push(line);
                }
            });
        }
    });

    if (coordinates.length === 0) return null;

    return {
        id: lineInfo.type === 'tram' ? `TRAM_${lineInfo.ref}` : `BUS_${lineInfo.ref}`,
        type: lineInfo.type,
        name: `Ligne ${lineInfo.ref}`,
        trajectory: lineInfo.name, // Use static name for now as OSM name might be "Ligne A ..."
        color: `#${lineInfo.color}`,
        geoJson: {
            type: 'Feature',
            properties: {
                id: lineInfo.ref,
                color: `#${lineInfo.color}`
            },
            geometry: {
                type: 'MultiLineString',
                coordinates: coordinates
            }
        }
    };
}

async function main() {
    const results = [];

    for (const line of LINES) {
        const type = line.type === 'tram' ? 'tram' : 'bus';
        const elements = await fetchLine(line.ref, type);

        const converted = convertToGeoJSON(elements, line);
        if (converted) {
            results.push(converted);
        } else {
            console.warn(`No geometry found for ${line.ref}`);
        }

        // Polite delay
        await new Promise(r => setTimeout(r, 1000));
    }

    const fileContent = `/**
 * AUTO-GENERATED FILE FROM OPENSTREETMAP DATA
 * Generated by fetch_osm_lines.js
 */

export interface TransportLine {
    id: string;
    type: 'tram' | 'bus';
    name: string;
    trajectory: string;
    color: string;
    geoJson?: any; // Feature<MultiLineString>
}

export const TRANSPORT_LINES: TransportLine[] = ${JSON.stringify(results, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Generated ${OUTPUT_FILE} with ${results.length} lines.`);
}

main();
